export default {
  name: 'opportunity',
  title: 'Opportunities',
  type: 'document',
  fields: [
    { name: 'title', title: 'Title', type: 'string', validation: (r: any) => r.required() },
    { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title' }, validation: (r: any) => r.required() },
    { name: 'openDate', title: 'Open Date', type: 'date' },
    { name: 'deadline', title: 'Deadline', type: 'date' },
    { name: 'lastUpdated', title: 'Last Updated', type: 'date' },
    { name: 'fundingType', title: 'Funding Type', type: 'string', options: { list: ['Full Fund', 'Full Tuition', 'Partial Fund'] } },
    { name: 'country', title: 'Country', type: 'string' },
    { name: 'numberOfRecipients', title: 'Number of Recipients', type: 'string' },
    { name: 'hostInstitution', title: 'Host Institution', type: 'string' },
    { name: 'levelOfStudy', title: 'Level of Study', type: 'string', options: { list: ["Bachelor's", "Master's", 'PhD'] } },
    { name: 'officialLink', title: 'Official Link', type: 'url' },
    { name: 'category', title: 'Category', type: 'string', options: { list: ['internship', 'fellowship'] } },
    { name: 'tags', title: 'Tags', type: 'array', of: [{ type: 'string' }] },
    { name: 'author', title: 'Author', type: 'string' },
    { name: 'excerpt', title: 'Excerpt', type: 'text' },
    { name: 'featuredImage', title: 'Featured Image', type: 'image', options: { hotspot: true } },
    { name: 'body', title: 'Body', type: 'array', of: [{ type: 'block' }, { type: 'image', options: { hotspot: true } }] },
  ],
}
